### ISSUE TITLE
user 'nobody' cannot see volume

### ISSUE THREAD

**Issue by Tepido** [aptalca/docker-rdp-calibre#8]
I managed to get the web interface and the calibre running on my synology without much trouble. But, when I run the setup for calibre, the only option I get for a library location is /nobody/<whatever>. I tried to see the volume where I created the calibre\library folder, but I can't get to it. I'm not sure what's going on, because I can't even see the 'nobody' folder on any of the shares on the synology

**Comment by aptalca** [comment]
Can you post your run command?

In the web gui, you should be able to select "/config" as the library location

**Comment by Tepido** [comment]
Here's a copy of what's running. I setup using the wizard.

![net1](https://cloud.githubusercontent.com/assets/17788025/13717781/e7b26ef8-e7b1-11e5-9b9b-86c4ff2c9590.PNG)
![net2](https://cloud.githubusercontent.com/assets/17788025/13717782/e7befb46-e7b1-11e5-81dc-dd47801b3f2c.PNG)

Here's what I see when I try and select the library folder.
![snip1](https://cloud.githubusercontent.com/assets/17788025/13717793/073f5b46-e7b2-11e5-898a-82ac96631c9d.PNG)

When I try to 'add books',  I'm unable to access the shares I created on the synology drive. I checked the mount, and it shows Volume1 as mounted under /dev/vg1/volume_1, but I can't browse to that folder (doesn't show up).

**Comment by aptalca** [comment]
It looks like you mounted two folders.

/Calibre/Library on synology is mounted in the container as /Library and
/Calibre/config on synology is mounted in the container as /config

If you want to navigate to the config folder, open the container's file manager (click on add books), double click on Computer, then double click on "/" for the main drive, and you'll see the two mounted folders as "Library" and "config"

If the books you're trying to add are in a different location on synology, create another mount point for that share

**Comment by Tepido** [comment]
Actually, that's where the problem is.. If you look at the second library, you can see that it's mounted under /nobody/Calibre Library.. The config is located under /config.

I've created a shared folder with the synology manager called 'Calibre', and set all the permissions, but I can't seem to get docker-rpd-calibre to access them. (I'm pretty sure I followed the install step by step, I entered a valid folder location for both the config and library.

I want the library to be mounted under \Calibre\Library, and the config to be under \Calibre\config.

I'm confused as to where the 'nobody' comes in?   For some reason, 'nobody' is not able to access the 'shares' on Calibre. I've tried logging in as root, and I start in 

STORAGE-2> pwd
/volume1/homes/admin
which is where I expect to start. 
of note, there is no 'home directory' for the user 'nobody'..There is no 'nobody' account (well, I can't create it in user manager on synology, says the user name is reserved for system use.

I 'think' I can get it all working, if I could just change the user account that docker-rdp-calibre runs under, but I've been unable to figure out how to do that.

**Comment by aptalca** [comment]
I think you're confused about how docker works.

Calibre is running inside a container which is based on ubuntu 14.04. Think of it as a vm that is only running calibre and nothing else. It is a separate operating system and therefore it doesn't natively access your synology shares or folders. It can only access its own internal files and whatever folders may be specifically mounted in the container settings.

In this case, you only mounted two folders and those folders should be accessible at /config and /Library "inside the container". The folder nobody is the user folder inside the container because calibre is running as user nobody within the ubuntu based container. Don't worry about that folder; it will always be there but you won't be using it. The "Calibre Library" folder, I have no idea how it came to be, I am guessing it was by mistake, or perhaps it was selected during first startup and Calibre created it. Based on your settings from the screenshot, there shouldn't be anything mounted there.

I suggest you start fresh. Pick two folders, one for config, and one for where you will import your books from. Mount those two locations.

When you open the gui the first time, select "/config" as the library location. Yes, both the config and the library will reside in the same location and that is how this container was set up (there is a way to separate them but I suggest not trying that until you get a good handle of how docker works).

Then you can add books from the second mount point.

I also recommend putting a couple of dummy files in those locations and test whether you can see them within the container so you can make sure you set the mount points correctly.

**Comment by Daopr** [comment]
I meet the permission problem, too.And I solve it by trying many times 
Thanks for your explanations. And I find that the problem is indeed existed on synology.
Do not use ssh to add this docker, just use the docker suite.
then permit group " Users " to rw the directories(include subs.) you just mount on this container.
then calibre could rw them, whatever nobody inside of the container.
